### ISSUE TITLE
connect "follow" button to node subscription system for wiki pages

### ISSUE THREAD

**Issue by jywarren** [jywarren/plots2#116]
there's no other way to see if a page has been updated!

**Comment by jywarren** [comment]
really? wheeee!

OK so I have to start using feature branches and carefully rebasing now
that there's more activity on this repo.

I'm going to go in and start moving jywarren/plots2 issues over!

**Comment by btbonval** [comment]
20 minutes ago? I was working on something else entirely. You must have merged commits of mine on a feature branch.

**Comment by btbonval** [comment]
oh no! my upstream must be set to jywarren!

**Comment by btbonval** [comment]
nope. How did I get a commit from 14 days ago in your repo?
