### ISSUE TITLE
mailing list powertag can break wiki pages

### ISSUE THREAD

**Issue by jessibreen** [jywarren/plots2#188]
The Public Lab Writing Group's wiki page, inventively titled, "Public Lab Writing Group (PLWG)," seems to both exist and not exist.  You can search for the page, but when you try to open the resulting link an error message questioning your ability to use a search bar appears.  I'm not sure if this is analogous to the poison killing the cat or maybe the cat just starved to death while trapped in the box. Either way, I would like the page back.  Otherwise, I will have to take to IRC and lurk silently on the publiclab channel until my demands are met or I decide to go take a nap.

**Comment by jywarren** [comment]
Moving this issue to https://github.com/publiclab/plots2/issues/219
