### ISSUE TITLE
research popup menu too long for netbook screens and can't scroll

### ISSUE THREAD

**Issue by btbonval** [jywarren/plots2#198]
On my netbook, the Research popup menu goes to the bottom of my browser screen, ending at "Providence." Maybe there is nothing past that, maybe there is, but I cannot tell either way.

If I scroll down, the page in back scrolls, but the white popup menu remains fixed. I can't access the whole thing.

**Comment by jywarren** [comment]
moving to https://github.com/publiclab/plots2/issues/230
