### ISSUE TITLE
wiki#root and wiki#show are redundant and out of sync

### ISSUE THREAD

**Issue by btbonval** [jywarren/plots2#199]
`wiki#root` can be used to retrieve any wiki page at all, but it is only used in the case of `/:id`

`wiki#show` is also used to retrieve wiki pages, but it is used for `/wiki/:id`.

there's not any good reason to have two such functions. `routes.rb` can point both at the same wiki function. Might as well pick one or the other function and stick to it.

**Comment by jywarren** [comment]
moving to https://github.com/publiclab/plots2/issues/220
