### ISSUE TITLE
Markdown for tables in comments

### ISSUE THREAD

**Issue by Fastie** [jywarren/plots2#204]
In a [comment on a research note](http://publiclab.org/notes/cfastie/11-07-2013/focus-on-filters), this markdown for a table:
`| ......Camera......|.............. Variable Iris..........   |     .......ND filter(s)  |  
| -------------------------- |:-----------------------:| :--------------------:|  
| SD1100| no | yes|  
| A2200 | no     |   yes |  
| A495 | yes (2 round holes)    |    ? |  
| SX120 | yes (~6 leaves)    |    ? |  
| S95 | yes (6 leaves)     |    ? |  `

parses correctly in preview mode but does not parse to a table like this when published:

| ......Camera......|.............. Variable Iris..........   |     .......ND filter(s)  |  
| -------------------------- |:-----------------------:| :--------------------:|  
| SD1100| no | yes|  
| A2200 | no     |   yes |  
| A495 | yes (2 round holes)    |    ? |  
| SX120 | yes (~6 leaves)    |    ? |  
| S95 | yes (6 leaves)     |    ? |

**Comment by jywarren** [comment]
moving to https://github.com/publiclab/plots2/issues/234
