### ISSUE TITLE
better interface for research note response feature

### ISSUE THREAD

**Issue by nathanathan** [jywarren/plots2#211]
Some research notes have a "This is a response to..." item in the side bar. I would like to edit [one of my notes](http://publiclab.org/notes/nathanathan/12-04-2013/glow-in-the-dark-paint-photos) to have one, but I can't seem to find a way to do it.

Also, I don't see anything that indicates whether a note has response notes and where the responses are. I think that could be very useful for following lines of research conducted by multiple people.

**Comment by jywarren** [comment]
moving to https://github.com/publiclab/plots2/issues/221
