### ISSUE TITLE
More visible store link

### ISSUE THREAD

**Issue by Rillwater** [jywarren/plots2#233]
![screen shot 2014-06-05 at 11 45 58 am](https://cloud.githubusercontent.com/assets/7808553/3192088/f745097e-ece1-11e3-8cce-62ed166ca931.png)
I would like to see a more visible store link.  Several interview candidates mentioned difficultly in finding a link to the store.  
Lets see if sales jump!

**Comment by jywarren** [comment]
Closing this, but @Nataliegurl if you can get some +1s from other staff on this (header real estate is pretty carefully designed by staff) feel free to open a new issue at https://github.com/publiclab/plots2/issues/
